import { StyleSheet } from 'react-native';

export const  styles = StyleSheet.create({
    scroll: { paddingVertical: 20, alignItems: "center" },
    card: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
        width: "100%",
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    title: { fontSize: 22, fontWeight: "700", marginBottom: 20, color: "#111827", textAlign: "center" },
    label: { fontSize: 14, marginBottom: 6, color: "#374151" },
    input: {
        borderWidth: 1,
        borderRadius: 10,
        padding: 12,
        fontSize: 16,
        color: "#111827",
        backgroundColor: "#fff",
    },
    row: { flexDirection: "row", gap: 12 },
    half: { flex: 1 },
    linkRow: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
    consentRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", marginVertical: 8 },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: "#d1d5db",
        marginRight: 8,
        alignItems: "center",
        justifyContent: "center",
    },
    checkboxChecked: { backgroundColor: "#111827", borderColor: "#111827" },
    consentText: { flexShrink: 1, marginHorizontal: 6, color: "#374151", textAlign: "center"},
    consentLink: { color: "#008080", fontWeight: "600" },
    requiredStar: { color: "#ef4444", marginLeft: 4 },
    errorText: { color: "#ef4444", fontSize: 12, marginTop: 4 },
    confirmBtn: {
        backgroundColor: "#111827",
        paddingVertical: 14,
        borderRadius: 999,
        alignItems: "center",
        marginTop: 16,
    },
    confirmText: { color: "#fff", fontSize: 16, fontWeight: "600" },

    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    modalBox: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
        width: "90%",
        maxWidth: 360,
        alignItems: "center",
    },
    modalBoxLarge: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
        width: "90%",
        maxWidth: 400,
        maxHeight: "80%",
        alignItems: "center",
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "700",
        marginBottom: 10,
        textAlign: "center",
    },
    modalBody: { fontSize: 14, color: "#374151", lineHeight: 20 },
    modalBtnSmall: {
        marginTop: 14,
        paddingVertical: 10,
        paddingHorizontal: 28,
        backgroundColor: "#111827",
        borderRadius: 999,
    },
    modalBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
    modalHeader: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        marginBottom: 12,
    },
    centerRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center", // ✅ centers horizontally
        marginBottom: 12,
    },
    linkText: {
        marginLeft: 6,
        color: "#6b7280",
        textAlign: "center",
    },
    consentWrapper: {
        alignItems: "center",    // centers both row + error
        marginVertical: 8,
    },
    errorTextCentered: {
        color: "#ef4444",
        fontSize: 12,
        marginTop: 4,
        textAlign: "center",     // ✅ error directly under the group
    },
})