import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const forgotPasswordStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 60,
    paddingVertical: 60,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    top: 60,
    left: 30,
    padding: 10,
    zIndex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    color: '#374151',
    textAlign: 'center',
    letterSpacing: 0.5,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  description: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 40,
    paddingHorizontal: 20,
    lineHeight: 20,
    fontFamily: 'BalooBhaijaan2_400Regular',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: 300,
    marginBottom: 40,
    backgroundColor: 'transparent',
    borderRadius: 0,
    paddingHorizontal: 0,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  inputIcon: {
    marginRight: 12,
    color: '#9ca3af',
    opacity: 0.7,
  },
  textInput: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    fontFamily: 'BalooBhaijaan2_400Regular',
    paddingVertical: 0,
  },
  sendButton: {
    width: width * 0.6,
    maxWidth: 200,
    paddingVertical: 12,
    paddingHorizontal: 32,
    backgroundColor: '#000000',
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  sendButtonDisabled: {
    backgroundColor: '#9ca3af',
  },
  sendButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  signInContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  signInText: {
    color: '#9ca3af',
    fontSize: 14,
    fontWeight: '200',
    fontFamily: 'BalooBhaijaan2_400Regular',
  },
  signInLink: {
    color: '#008080',
    fontSize: 14,
    fontWeight: '900',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    letterSpacing: 0.5,
  },
});