import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const roleSelectionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 20,
    letterSpacing: 0.5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  subtitle: {
    fontSize: 16,
    fontFamily: 'BalooBhaijaan2_400Regular',
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 40,
    letterSpacing: 0.3,
  },
  roleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    paddingHorizontal: 20,
    width: '100%',
    maxWidth: 320,
  },
  roleButton: {
    width: 120,
    height: 120,
    borderWidth: 2,
    borderColor: '#d1d5db',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    marginHorizontal: 10,
  },
  selectedRoleButton: {
    borderColor: '#20A7B1',
    borderWidth: 3,
    backgroundColor: '#f0fdff',
  },
  iconContainer: {
    position: 'absolute',
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  iconMaskContainer: {
    width: 40,
    height: 40,
  },
  iconMask: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  gradientIcon: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roleLabel: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'BalooBhaijaan2_400Regular',
    color: '#374151',
    textAlign: 'center',
    marginTop: 65,
    letterSpacing: 0.3,
  },
  selectedRoleLabel: {
    color: '#20A7B1',
    fontWeight: '700',
  },
  descriptionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 40,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  descriptionText: {
    fontSize: 14,
    fontFamily: 'BalooBhaijaan2_400Regular',
    color: '#6b7280',
    marginLeft: 6,
    letterSpacing: 0.3,
  },
  confirmButton: {
    width: width * 0.5,
    maxWidth: 200,
    paddingVertical: 12,
    paddingHorizontal: 32,
    backgroundColor: '#000000',
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  disabledButton: {
    backgroundColor: '#9ca3af',
  },
  confirmButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  disabledButtonText: {
    color: '#d1d5db',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 24,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 24,
    letterSpacing: 0.5,
  },
  modalContent: {
    marginBottom: 32,
  },
  questionSection: {
    marginBottom: 24,
  },
  questionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  questionText: {
    fontSize: 16,
    fontFamily: 'BalooBhaijaan2_400Regular',
    color: '#6b7280',
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  answerContainer: {
    paddingVertical: 12,
    paddingLeft: 8,
  },
  answerText: {
    fontSize: 14,
    fontFamily: 'BalooBhaijaan2_400Regular',
    color: '#4b5563',
    lineHeight: 20,
    letterSpacing: 0.3,
  },
  underline: {
    height: 1,
    backgroundColor: '#e5e7eb',
    width: '100%',
  },
  modalCloseButton: {
    backgroundColor: '#000000',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  modalCloseButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    letterSpacing: 1,
    textAlign: 'center',
  },
});