import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const signUpStyles = StyleSheet.create({
  signUpContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 60,
    paddingVertical: 60,
  },
  signUpTitle: {
    fontSize: 28,
    fontWeight: '900',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    color: '#374151',
    textAlign: 'center',
    letterSpacing: 0.5,
    marginBottom: 30, // เพิ่ม spacing ระหว่าง title และ button
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: 300,
    marginBottom: 15,
    backgroundColor: 'transparent',
    borderRadius: 0,
    paddingHorizontal: 0,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d5db',
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  inputIcon: {
    marginRight: 12,
    color: '#9ca3af',
  },
  textInput: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    fontFamily: 'BalooBhaijaan2_400Regular',
    paddingVertical: 0,
  },
  eyeIcon: {
    padding: 5,
  },
  forgotPasswordContainer: {
    alignSelf: 'flex-end',
    marginBottom: 40,
    maxWidth: 300,
    width: '100%',
  },
  forgotPasswordText: {
    marginTop: 0,
    color: '#9ca3af',
    fontSize: 13,
    textAlign: 'right',
    fontFamily: 'BalooBhaijaan2_400Regular',
  },
  signUpSubmitButton: {
    width: width * 0.35, // ใช้ 60% ของหน้าจอ
    maxWidth: 150,
    paddingVertical: 10,
    paddingHorizontal: 32,
    backgroundColor: '#000000',
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  signUpSubmitButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  signInContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 15,
  },
  signInText: {
    color: '#9ca3af',
    fontSize: 14,
    fontWeight: '200',
    fontFamily: 'BalooBhaijaan2_400Regular',
  },
  signInLink: {
    color: '#008080',
    fontSize: 14,
    fontWeight: '900',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
    letterSpacing: 0.5,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    maxWidth: 300,
    marginTop: 0,
    marginBottom: 10,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e5e7eb',
  },
  dividerText: {
    color: '#9ca3af',
    fontSize: 14,
    paddingHorizontal: 15,
    fontFamily: 'BalooBhaijaan2_400Regular',
  },
  googleSignInButton: {
    width: 40,
    height: 40,
    borderRadius: 30,
    backgroundColor: '#6b7280',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
    shadowColor: 'transparent',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  googleIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  googleIcon: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'BalooBhaijaan2_600SemiBold',
  },
});